name: Publish Main Release

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  publish:
    uses: ./.github/workflows/publish.yml
    secrets: inherit
    with:
      create_release: true
      send_discord: true
      upload_to_google_drive: true
