name: Publish Release Candidate

on:
  push:
    branches:
      - release-candidate

jobs:
  publish:
    uses: ./.github/workflows/publish.yml
    secrets: inherit
    with:
      create_release: false
      send_discord: false
      upload_to_google_drive: true
